import { useState, useContext, useRef, useEffect } from 'react';
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { apiGetMetrics } from '../logic/apis.js';
import { CustomerContext } from './contexts.js';

const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#f97316'];

const tooltipStyle = {
  contentStyle: { background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: '6px', color: 'hsl(var(--foreground))' },
  labelStyle: { color: 'hsl(var(--foreground))' },
};

const ChartCard = ({ title, children, status }) => (
  <div className="rounded-lg border border-border bg-card p-6">
    <h2 className="text-lg font-semibold text-card-foreground mb-4">{title}</h2>
    <div style={{ height: '300px' }}>
      {status === 'loading' ? (
        <div className="h-full flex items-center justify-center text-sm text-muted-foreground">Loading...</div>
      ) : status === 'error' ? (
        <div className="h-full flex items-center justify-center text-sm text-destructive">Error loading data</div>
      ) : children}
    </div>
  </div>
);

export const Usage = () => {
  const isMounted = useRef(true);
  const customer = useContext(CustomerContext);

  const [sUCRP, setSUCRP] = useState("initial");
  const [sUYRP, setSUYRP] = useState("initial");
  const [sUCC, setSUCC] = useState("initial");
  const [sUYC, setSUYC] = useState("initial");
  const [sGCRP, setSGCRP] = useState("initial");
  const [sGY, setSGY] = useState("initial");

  const [dUCRP, setDUCRP] = useState(null);
  const [dUYRP, setDUYRP] = useState(null);
  const [dUCC, setDUCC] = useState(null);
  const [dUYC, setDUYC] = useState(null);
  const [dGCRP, setDGCRP] = useState(null);
  const [dGY, setDGY] = useState(null);

  const timeRange = () => {
    const now = new Date();
    const start = `${now.getFullYear() - 1}-${String(now.getMonth() + 1).padStart(2, "0")}-01 00:00:00`;
    const end = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")} ${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}:${String(now.getSeconds()).padStart(2, "0")}`;
    return { start, end };
  };

  const loadAll = async (customer) => {
    // Current usage by rate plan
    setSUCRP("loading");
    const r1 = await apiGetMetrics({ device_id: customer.device_id, name: "usage", order: "DESC" });
    if (r1 === false && isMounted.current) setSUCRP("error");
    else if (isMounted.current) { setDUCRP(r1.map(e => ({ name: e.dimension, value: parseFloat(e.value) / 1000 }))); setSUCRP("finished"); }

    // Yearly usage by rate plan
    setSUYRP("loading");
    const { start, end } = timeRange();
    const r2 = await apiGetMetrics({ device_id: customer.device_id, name: "usage", start, end });
    if (r2 === false && isMounted.current) setSUYRP("error");
    else if (isMounted.current) { setDUYRP(buildBarData(r2)); setSUYRP("finished"); }

    // Current usage by consumer
    setSUCC("loading");
    const r3 = await apiGetMetrics({ device_id: customer.device_id, name: "usage", aggregator: "consumer", order: "DESC" });
    if (r3 === false && isMounted.current) setSUCC("error");
    else if (isMounted.current) { setDUCC(r3.map(e => ({ name: e.dimension, value: parseFloat(e.value) / 1000 }))); setSUCC("finished"); }

    // Yearly usage by consumer
    setSUYC("loading");
    const r4 = await apiGetMetrics({ device_id: customer.device_id, name: "usage", aggregator: "consumer", start, end });
    if (r4 === false && isMounted.current) setSUYC("error");
    else if (isMounted.current) { setDUYC(buildBarData(r4)); setSUYC("finished"); }

    // Current generated by rate plan
    setSGCRP("loading");
    const r5 = await apiGetMetrics({ device_id: customer.device_id, name: "generated", order: "DESC" });
    if (r5 === false && isMounted.current) setSGCRP("error");
    else if (isMounted.current) { setDGCRP(r5.map(e => ({ name: e.dimension, value: parseFloat(e.value) / 1000 }))); setSGCRP("finished"); }

    // Yearly generated
    setSGY("loading");
    const r6 = await apiGetMetrics({ device_id: customer.device_id, name: "generated", start, end });
    if (r6 === false && isMounted.current) setSGY("error");
    else if (isMounted.current) { setDGY(buildBarData(r6)); setSGY("finished"); }
  };

  const buildBarData = (result) => {
    const dimensions = [...new Set(result.map(e => e.dimension))];
    const intervals = [...new Set(result.map(e => e.interval))];
    const data = intervals.map(interval => {
      const row = { interval };
      result.filter(e => e.interval === interval).forEach(e => { row[e.dimension] = parseFloat(e.value) / 1000; });
      return row;
    });
    return { data, dimensions };
  };

  useEffect(() => { return () => { isMounted.current = false; }; }, []);
  useEffect(() => { if (isMounted.current && customer) loadAll(customer); }, [customer]); // eslint-disable-line

  const renderPie = (data) => (
    data && data.length > 0 ? (
      <ResponsiveContainer width="100%" height="100%">
        <PieChart>
          <Pie data={data} cx="50%" cy="50%" innerRadius="40%" outerRadius="70%" dataKey="value" stroke="hsl(var(--card))">
            {data.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
          </Pie>
          <Tooltip {...tooltipStyle} formatter={(v) => [`${v.toFixed(2)} kWh`, 'Usage']} />
          <Legend formatter={(value) => <span style={{ color: 'hsl(var(--foreground))' }}>{value}</span>} />
        </PieChart>
      </ResponsiveContainer>
    ) : <div className="h-full flex items-center justify-center text-sm text-muted-foreground">No data available</div>
  );

  const renderBar = (barData, stacked = false) => (
    barData && barData.data.length > 0 ? (
      <ResponsiveContainer width="100%" height="100%">
        <BarChart data={barData.data}>
          <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
          <XAxis dataKey="interval" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} />
          <YAxis tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} />
          <Tooltip {...tooltipStyle} formatter={(v) => [`${v.toFixed(2)} kWh`]} />
          <Legend formatter={(value) => <span style={{ color: 'hsl(var(--foreground))' }}>{value}</span>} />
          {barData.dimensions.map((dim, i) => (
            <Bar key={dim} dataKey={dim} stackId={stacked ? "stack" : undefined} fill={COLORS[i % COLORS.length]} radius={stacked ? undefined : [4, 4, 0, 0]} />
          ))}
        </BarChart>
      </ResponsiveContainer>
    ) : <div className="h-full flex items-center justify-center text-sm text-muted-foreground">No data available</div>
  );

  return (
    <div className="px-6 py-4 space-y-4">
      <nav className="flex items-center gap-1.5 text-sm text-muted-foreground">
        <a href="#/" className="hover:text-foreground transition-colors no-underline text-muted-foreground">Dashboard</a>
        <span>/</span>
        <span className="text-foreground">Energy usage and production</span>
      </nav>
      <h1 className="text-2xl font-semibold tracking-tight text-foreground">Energy usage and production</h1>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <ChartCard title="Usage this month by rate plan" status={sUCRP}>{renderPie(dUCRP)}</ChartCard>
        <div className="lg:col-span-3"><ChartCard title="Usage over the past 12 months" status={sUYRP}>{renderBar(dUYRP, true)}</ChartCard></div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <ChartCard title="Top consumers this month" status={sUCC}>{renderPie(dUCC)}</ChartCard>
        <div className="lg:col-span-3"><ChartCard title="Top consumers over the past 12 months" status={sUYC}>{renderBar(dUYC, true)}</ChartCard></div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <ChartCard title="Generated this month by rate plan" status={sGCRP}>{renderPie(dGCRP)}</ChartCard>
        <div className="lg:col-span-3"><ChartCard title="Generation over the past 12 months" status={sGY}>{renderBar(dGY)}</ChartCard></div>
      </div>
    </div>
  );
};
